---
language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "stable"
cache:
  directories:
    - node_modules
deploy:
  provider: script
  script: yarn install && yarn run deploy
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
  script: yarn install && yarn run deploy
  skip_cleanup: true
